// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // CLI commands (migrate, studio) use the Session pooler connection —
    // see the DIRECT_URL comment in .env.example for why (transaction-mode
    // pooling breaks migrations; Supabase's true direct host is IPv6-only
    // and unreachable from Vercel).
    url: process.env["DIRECT_URL"],
  },
});
