// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // CLI commands (migrate, studio) use the direct connection — migrations
    // and advisory locks don't work reliably through a transaction-mode
    // pooler like Supabase's Supavisor.
    url: process.env["DIRECT_URL"],
  },
});
